services:
  db:
    image: postgres:16
    container_name: hobbyhub-db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data'

volumes:
  db_data:
  