app = "hobbyhub-api"
primary_region = "sea"

[build]
  image = "ghcr.io/andremunay/hobbyhub-api"

[env]
  PORT = "8080"

[vm]
  memory = 1024
  cpu_kind =  "shared"
  cpus = 1

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "connections"
    soft_limit = 1000
    hard_limit = 2000

  [[services.checks]]
    type = "http"
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/actuator/health"
    protocol = "http"
