spring:
  config:
    import: "optional:dotenv:.env"

  application:
    name: hobbyhub

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: repo,read:user

  main:
    banner-mode: "off"

  # --- Liquibase ---
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

# --- Secrets & Configuration ---
github:
  oauth:
    client-id: ${OAUTH_CLIENT_ID}    # injected via GitHub Actions
    client-secret: ${OAUTH_CLIENT_SECRET}

flyio:
  token: ${FLY_API_TOKEN}

registry:
  username: ${REGISTRY_USERNAME}
  password: ${REGISTRY_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: hobbyhub-api
  endpoint:
    prometheus:
      enabled: true
