spring:
  config:
    import: "optional:dotenv:.env"

  application:
    name: hobbyhub

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: repo,read:user

  main:
    banner-mode: "off"
  jpa:
    open-in-view: false

  # --- Liquibase ---
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

  datasource:
    url: ${JDBC_DATABASE_URL}
    driver-class-name: org.postgresql.Driver

server:
  address: 0.0.0.0
  port: 8080

# --- Secrets & Configuration ---
github:
  oauth:
    client-id: ${OAUTH_CLIENT_ID}    # injected via GitHub Actions
    client-secret: ${OAUTH_CLIENT_SECRET}

flyio:
  token: ${FLY_API_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: hobbyhub-api
