global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hobbyhub-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['hobbyhub-api.internal:8080']
