name: CI-CD

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ "**" ]

env:
  REGISTRY: ghcr.io/andremunay/hobbyhub-api

jobs:

  build-test:
    runs-on: ubuntu-latest
    

    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      OAUTH_CLIENT_ID: ${{ secrets.OAUTH_CLIENT_ID }}
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache Testcontainers
        uses: actions/cache@v4
        with:
          path: ~/.testcontainers
          key: ${{ runner.os }}-testcontainers-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-testcontainers-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Run Tests (with coverage)
        run: ./mvnw -B clean verify

      - name: Archive JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}:pr-${{ github.event.pull_request.number }}
            ${{ env.REGISTRY }}:${{ github.sha }}

  deploy-prod:
    if: github.event_name == 'push'
    needs: build-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: superfly/flyctl-actions@1.4
        with:
          args: >
            deploy
            --remote-only
            --image ${{ env.REGISTRY }}:${{ github.sha }}
            --app hobbyhub-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REGISTRY_AUTH_USER: ${{ secrets.REGISTRY_AUTH_USER }}
          REGISTRY_AUTH_TOKEN: ${{ secrets.REGISTRY_AUTH_TOKEN }}
