name: CI-CD

# Trigger on any push to any branch, but ignore markdown file changes.
# Also triggers when a PR is closed (e.g., for cleanup if needed).
on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
  pull_request:
    types: [closed]

# Common environment variable for Docker image naming
env:
  REGISTRY: ghcr.io/andremunay/hobbyhub-api

jobs:
  # Skip full build pipeline on main (handled by deploy-prod), run for all other branches
  build-test:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      # Integration test DB (used by Testcontainers)
      POSTGRES_DB:     ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER:   ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      # OAuth secrets required during test bootstrapping
      OAUTH_CLIENT_ID:     ${{ secrets.OAUTH_CLIENT_ID }}
      OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}

      # SonarCloud for static analysis and coverage metrics
      SONAR_TOKEN:        ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY:  ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache Testcontainers
        uses: actions/cache@v4
        with:
          path: ~/.testcontainers
          key: ${{ runner.os }}-testcontainers-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-testcontainers-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Run Tests (with coverage)
        run: ./mvnw -B clean verify

      - name: Archive JaCoCo Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Analyze with SonarCloud
        run: |
          ./mvnw verify sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ env.SONAR_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push branch image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ github.head_ref || github.ref_name }}

      - name: Push :latest tag (main only)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}:latest

  deploy-prod:
    # Only runs on push to main branch
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Fly.io
        uses: superfly/flyctl-actions@1.4
        with:
          args: >
            deploy
            --image ${{ env.REGISTRY }}:latest
            --app hobbyhub-api
        env:
          FLY_API_TOKEN:           ${{ secrets.FLY_API_TOKEN }}
          REGISTRY_AUTH_USERNAME:  ${{ secrets.GHCR_USERNAME }}
          REGISTRY_AUTH_TOKEN:     ${{ secrets.GHCR_TOKEN }}
